Accounting:
  children:
    db_servers:
      hosts:
        DB:
          ansible_host: 3.129.155.219 
          ansible_ssh_private_key_file: /home/ubuntu/terraform/homework-test-db-us-east-2.pem
    lb_servers:
      hosts:
        LB:
          ansible_host: 3.133.201.49
          ansible_ssh_private_key_file: /home/ubuntu/terraform/homework-test-lb-us-east-2.pem
    web_servers:
      hosts:
        WEB:
          ansible_host: 3.138.83.163
          ansible_ssh_private_key_file: /home/ubuntu/terraform/homework-test-web-us-east-2.pem
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    ansible_user: ubuntu
    app_name: Test
    db_port: 27017
    db_servers:
    - 192.168.0.13
    lb_port: 80
    web_server_port: 8080
    web_servers:
    - 192.168.0.12
